frase = str(input('Digite seu nome completo: ')).strip()
separa = frase.split()
print('Muito prazer em te conhecer {}'.format(frase))
print('Seu primeiro nome é {}'.format(separa[0]))
print('Seu último nome é {}'.format(separa[len(separa)-1]))
